; Script generated by the HM NIS Edit Script Wizard.
; HM NIS Edit Wizard helper defines
!include nsDialogs.nsh
!define PRODUCT_NAME "AsteriskNotifier"
!define PRODUCT_VERSION "1.0.9"
!define PRODUCT_PUBLISHER "Xtelekom"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\AsteriskNotifier.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsteriskNotifier"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

!include nsDialogs.nsh
!include LogicLib.nsh

var cnfCheckBox
Var cnfCheckBox_State

var cnfActivate
Var cnfActivate_State

Var cnfWindow
Var cnfActivateWindow

Var lbServer
Var edServer
Var edServer_text

Var lbPort
Var edPort
Var edPort_text

Var lbUser
Var edUser
Var edUser_text

Var lbMyNumber
Var edMyNumber
Var edMyNumber_text

Var lbOriginateContext
Var edOriginateContext
Var edOriginateContext_text

Var lbOriginatePriority
Var edOriginatePriority
Var edOriginatePriority_text

Var lbOriginateTimeout
Var edOriginateTimeout
Var edOriginateTimeout_text

Var lbOnlyImportant
Var edOnlyImportant
Var edOnlyImportant_text

Var lbACTIVATION_EMAIL
Var edACTIVATION_EMAIL
Var edACTIVATION_EMAIL_text

Var lbACTIVATION_PASSWORD
Var edACTIVATION_PASSWORD
Var edACTIVATION_PASSWORD_text

Var lbASTERISK_MANAGER_PASSWORD
Var edASTERISK_MANAGER_PASSWORD
Var edASTERISK_MANAGER_PASSWORD_text

Var lbMYSQL_DATABASE
Var edMYSQL_DATABASE
Var edMYSQL_DATABASE_text

Var lbMYSQL_DataSource
Var edMYSQL_DataSource
Var edMYSQL_DataSource_text

Var lbMYSQL_UserId
Var edMYSQL_UserId
Var edMYSQL_UserId_text

Var lbMYSQL_Password
Var edMYSQL_Password
Var edMYSQL_Password_text



XPStyle on


; MUI 1.67 compatible ------

!include "MUI.nsh"
; Welcome page


!insertmacro MUI_PAGE_WELCOME


!insertmacro MUI_PAGE_LICENSE "license.rtf"

; Directory page

!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page

Page custom nsDialogsPage nsDialogsPageLeave
Page custom nsActivate nsActivateLeave


!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe" 
;!define MUI_FINISHPAGE_SHOWREADME "readme.rtf"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES


; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Russian"

; MUI end ------


Function nsDialogsPage

	nsDialogs::Create 1018
	Pop $cnfWindow

	${If} $cnfWindow == error
		Abort
	${EndIf}

	${NSD_CreateCheckbox} 0 0 100% 12u% "Создать файл настроек AsteriskNotifier.exe.config (не требуется при обновлении)"
	Pop $cnfCheckBox
	${NSD_OnClick} $cnfCheckBox EnDisableButton
 
	${NSD_CreateLabel} 0 16u 140u 12u "IP адрес сервера"
	Pop $lbServer
	${NSD_CreateText} 145u 16u 150u 12u "192.168.0.2"
	Pop $edServer

	${NSD_CreateLabel} 0 30u 140u 12u "Порт подключения (5038)"
	Pop $lbPort
	${NSD_CreateText} 145u 30u 150u 12u "5038"
	Pop $edPort

	${NSD_CreateLabel} 0 44u 140u 12u "Пользователь"
	Pop $lbUser
	${NSD_CreateText} 145u 44u 150u 12u "adm123"
	Pop $edUser

	${NSD_CreateLabel} 0 58u 140u 12u "Номер (SIP/XXX)"
	Pop $lbMyNumber
	${NSD_CreateText} 145u 58u 150u 12u "SIP/100"
	Pop $edMyNumber

	${NSD_CreateLabel} 0 72u 140u 12u "Контекст оригинации"
	Pop $lbOriginateContext
	${NSD_CreateText} 145u 72u 150u 12u "from-internal"
	Pop $edOriginateContext

	${NSD_CreateLabel} 0 86u 140u 12u "Приоритет оригинации"
	Pop $lbOriginatePriority
	${NSD_CreateText} 145u 86u 150u 12u "1"
	Pop $edOriginatePriority

	${NSD_CreateLabel} 0 100u 140u 12u "Таймаут оригинации (мс)"
	Pop $lbOriginateTimeout
	${NSD_CreateText} 145u 100u 150u 12u "15000"
	Pop $edOriginateTimeout

	${NSD_CreateLabel} 0 114u 140u 12u "Показывать только важные контакты"
	Pop $lbOnlyImportant
	${NSD_CreateText} 145u 114u 150u 12u "False"
	Pop $edOnlyImportant



	${If} ${FileExists} "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe.config"

	EnableWindow $lbServer 0
	EnableWindow $edServer 0

	EnableWindow $lbPort 0
	EnableWindow $edPort 0

	EnableWindow $lbUser 0
	EnableWindow $edUser 0

	EnableWindow $lbMyNumber 0
	EnableWindow $edMyNumber 0

	EnableWindow $lbOriginateContext 0
	EnableWindow $edOriginateContext 0

	EnableWindow $lbOriginatePriority 0
	EnableWindow $edOriginatePriority 0

	EnableWindow $lbOriginateTimeout 0
	EnableWindow $edOriginateTimeout 0

	EnableWindow $lbOnlyImportant 0
	EnableWindow $edOnlyImportant 0

 	${NSD_SetState} $cnfCheckBox 0
${Else}
        
	EnableWindow $lbServer 1
	EnableWindow $edServer 1

	EnableWindow $lbPort 1
	EnableWindow $edPort 1

	EnableWindow $lbUser 1
	EnableWindow $edUser 1

	EnableWindow $lbMyNumber 1
	EnableWindow $edMyNumber 1

	EnableWindow $lbOriginateContext 1
	EnableWindow $edOriginateContext 1

	EnableWindow $lbOriginatePriority 1
	EnableWindow $edOriginatePriority 1

	EnableWindow $lbOriginateTimeout 1
	EnableWindow $edOriginateTimeout 1

	EnableWindow $lbOnlyImportant 1
	EnableWindow $edOnlyImportant 1
 	${NSD_SetState} $cnfCheckBox 1

${EndIf}

	nsDialogs::Show

FunctionEnd

Function nsDialogsPageLeave
 	CreateDirectory "$APPDATA\AsteriskNotifier"
        ${NSD_GetState} $cnfCheckBox $cnfCheckBox_State
        ${NSD_GetText} $edServer $edServer_text
        ${NSD_GetText} $edPort $edPort_text
        ${NSD_GetText} $edUser $edUser_text
        ${NSD_GetText} $edMyNumber $edMyNumber_text
        ${NSD_GetText} $edOriginateContext $edOriginateContext_text
        ${NSD_GetText} $edOriginatePriority $edOriginatePriority_text
        ${NSD_GetText} $edOriginateTimeout $edOriginateTimeout_text
        ${NSD_GetText} $edOnlyImportant $edOnlyImportant_text

;        MessageBox MB_OK $cnfCheckBox_State
 	${If} $cnfCheckBox_State == ${BST_CHECKED}
		FileOpen $1 $APPDATA\AsteriskNotifier\AsteriskNotifier.exe.config w
		FileWrite $1 '<?xml version="1.0"?>$\r$\n'
		FileWrite $1 '<configuration>$\r$\n'
		FileWrite $1 '    <configSections>$\r$\n'
		FileWrite $1 '        <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >$\r$\n'
		FileWrite $1 '            <section name="AsteriskNotifier.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />$\r$\n'
		FileWrite $1 '        </sectionGroup>$\r$\n'
		FileWrite $1 '    </configSections>$\r$\n'
		FileWrite $1 '    <startup> $\r$\n'
		FileWrite $1 '        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>$\r$\n'
		FileWrite $1 '    </startup>$\r$\n'
		FileWrite $1 '    <applicationSettings>$\r$\n'
		FileWrite $1 '        <AsteriskNotifier.Properties.Settings>$\r$\n'
		FileWrite $1 '            <setting name="Server" serializeAs="String">$\r$\n'
		FileWrite $1 '	                <value>$edServer_text</value>$\r$\n'
		FileWrite $1 '            </setting>$\r$\n'
		FileWrite $1 '            <setting name="Port" serializeAs="String">$\r$\n'
		FileWrite $1 '                <value>$edPort_text</value>$\r$\n'
		FileWrite $1 '            </setting>$\r$\n'
		FileWrite $1 '            <setting name="User" serializeAs="String">$\r$\n'
		FileWrite $1 '                <value>$edUser_text</value>$\r$\n'
		FileWrite $1 '            </setting>$\r$\n'
		FileWrite $1 '            <setting name="MyNumber" serializeAs="String">$\r$\n'
		FileWrite $1 '                <value>$edMyNumber_text</value>$\r$\n'
		FileWrite $1 '            </setting>$\r$\n'
		FileWrite $1 '            <setting name="OriginateContext" serializeAs="String">$\r$\n'
		FileWrite $1 '                <value>$edOriginateContext_text</value>$\r$\n'
		FileWrite $1 '            </setting>$\r$\n'
		FileWrite $1 '            <setting name="OriginatePriority" serializeAs="String">$\r$\n'
		FileWrite $1 '                <value>$edOriginatePriority_text</value>$\r$\n'
		FileWrite $1 '            </setting>$\r$\n'
		FileWrite $1 '            <setting name="OriginateTimeout" serializeAs="String">$\r$\n'
		FileWrite $1 '                <value>$edOriginateTimeout_text</value>$\r$\n'
		FileWrite $1 '            </setting>$\r$\n'
		FileWrite $1 '            <setting name="OnlyImportant" serializeAs="String">$\r$\n'
		FileWrite $1 '                <value>$edOnlyImportant_text</value>$\r$\n'
		FileWrite $1 '            </setting>$\r$\n'
		FileWrite $1 '        </AsteriskNotifier.Properties.Settings>$\r$\n'
		FileWrite $1 '    </applicationSettings>$\r$\n'
		FileWrite $1 '</configuration>$\r$\n'

		FileClose $1
	${EndIf}

FunctionEnd


Function EnDisableButton
	Pop $cnfCheckBox

	${NSD_GetState} $cnfCheckBox $0

	${If} $0 == 1
        
	EnableWindow $lbServer 1
	EnableWindow $edServer 1

	EnableWindow $lbPort 1
	EnableWindow $edPort 1

	EnableWindow $lbUser 1
	EnableWindow $edUser 1

	EnableWindow $lbMyNumber 1
	EnableWindow $edMyNumber 1

	EnableWindow $lbOriginateContext 1
	EnableWindow $edOriginateContext 1

	EnableWindow $lbOriginatePriority 1
	EnableWindow $edOriginatePriority 1

	EnableWindow $lbOriginateTimeout 1
	EnableWindow $edOriginateTimeout 1

	EnableWindow $lbOnlyImportant 1
	EnableWindow $edOnlyImportant 1

	${Else}
	EnableWindow $lbServer 0
	EnableWindow $edServer 0

	EnableWindow $lbPort 0
	EnableWindow $edPort 0

	EnableWindow $lbUser 0
	EnableWindow $edUser 0

	EnableWindow $lbMyNumber 0
	EnableWindow $edMyNumber 0

	EnableWindow $lbOriginateContext 0
	EnableWindow $edOriginateContext 0

	EnableWindow $lbOriginatePriority 0
	EnableWindow $edOriginatePriority 0

	EnableWindow $lbOriginateTimeout 0
	EnableWindow $edOriginateTimeout 0

	EnableWindow $lbOnlyImportant 0
	EnableWindow $edOnlyImportant 0
	${EndIf}

	${NSD_GetState} $cnfCheckBox $cnfCheckBox_State
;        MessageBox MB_OK $cnfCheckBox_State
FunctionEnd



;-------------------------------------------------------------------------------------------------------------------------




Function nsActivate

	nsDialogs::Create 1018
	Pop $cnfActivateWindow

	${If} $cnfActivateWindow == error
		Abort
	${EndIf}

	${NSD_CreateCheckbox} 0 0 100% 12u% "Создать файл активации firstrun (не требуется при обновлении)"
	Pop $cnfActivate
	${NSD_OnClick} $cnfActivate cnfActivateClick
 
	${NSD_CreateLabel} 0 16u 140u 12u "@Почта"
	Pop $lbACTIVATION_EMAIL
	${NSD_CreateText} 145u 16u 150u 12u "username@domain.com"
	Pop $edACTIVATION_EMAIL

	${NSD_CreateLabel} 0 30u 140u 12u "Пароль активации"
	Pop $lbACTIVATION_PASSWORD
	${NSD_CreateText} 145u 30u 150u 12u ""
	Pop $edACTIVATION_PASSWORD

	${NSD_CreateLabel} 0 44u 140u 12u "Пароль доступа к asterisk"
	Pop $lbASTERISK_MANAGER_PASSWORD
	${NSD_CreateText} 145u 44u 150u 12u ""
	Pop $edASTERISK_MANAGER_PASSWORD

	${NSD_CreateLabel} 0 58u 140u 12u "База MYSQL"
	Pop $lbMYSQL_DATABASE
	${NSD_CreateText} 145u 58u 150u 12u "asteriskcdrdb"
	Pop $edMYSQL_DATABASE

	${NSD_CreateLabel} 0 72u 140u 12u "IP адрес сервера БД"
	Pop $lbMYSQL_DataSource
	${NSD_CreateText} 145u 72u 150u 12u "192.168.0.2"
	Pop $edMYSQL_DataSource

	${NSD_CreateLabel} 0 86u 140u 12u "MySQL логин"
	Pop $lbMYSQL_UserId
	${NSD_CreateText} 145u 86u 150u 12u "asteriskuser"
	Pop $edMYSQL_UserId

	${NSD_CreateLabel} 0 100u 140u 12u "MySQL пароль"
	Pop $lbMYSQL_Password
	${NSD_CreateText} 145u 100u 150u 12u ""
	Pop $edMYSQL_Password



	${If} ${FileExists} "$APPDATA\AsteriskNotifier\protected.db"

	EnableWindow $lbACTIVATION_EMAIL 0
	EnableWindow $edACTIVATION_EMAIL 0
	            
	EnableWindow $lbACTIVATION_PASSWORD 0
	EnableWindow $edACTIVATION_PASSWORD 0
	            
	EnableWindow $lbASTERISK_MANAGER_PASSWORD 0
	EnableWindow $edASTERISK_MANAGER_PASSWORD 0
	            
	EnableWindow $lbMYSQL_DATABASE 0
	EnableWindow $edMYSQL_DATABASE 0
	            
	EnableWindow $lbMYSQL_DataSource 0
	EnableWindow $edMYSQL_DataSource 0
	            
	EnableWindow $lbMYSQL_UserId 0
	EnableWindow $edMYSQL_UserId 0
	            
	EnableWindow $lbMYSQL_Password 0
	EnableWindow $edMYSQL_Password 0

 	${NSD_SetState} $cnfActivate 0
${Else}
        
	EnableWindow $lbACTIVATION_EMAIL 1
	EnableWindow $edACTIVATION_EMAIL 1
	            
	EnableWindow $lbACTIVATION_PASSWORD 1
	EnableWindow $edACTIVATION_PASSWORD 1
	            
	EnableWindow $lbASTERISK_MANAGER_PASSWORD 1
	EnableWindow $edASTERISK_MANAGER_PASSWORD 1
	            
	EnableWindow $lbMYSQL_DATABASE 1
	EnableWindow $edMYSQL_DATABASE 1
	            
	EnableWindow $lbMYSQL_DataSource 1
	EnableWindow $edMYSQL_DataSource 1
	            
	EnableWindow $lbMYSQL_UserId 1
	EnableWindow $edMYSQL_UserId 1
	            
	EnableWindow $lbMYSQL_Password 1
	EnableWindow $edMYSQL_Password 1

 	${NSD_SetState} $cnfActivate 1

${EndIf}

	nsDialogs::Show

FunctionEnd

Function nsActivateLeave

	CreateDirectory "$APPDATA\AsteriskNotifier"

        ${NSD_GetState} $cnfActivate $cnfActivate_State

        ${NSD_GetText} $edACTIVATION_EMAIL $edACTIVATION_EMAIL_text         
        ${NSD_GetText} $edACTIVATION_PASSWORD $edACTIVATION_PASSWORD_text      
        ${NSD_GetText} $edASTERISK_MANAGER_PASSWORD $edASTERISK_MANAGER_PASSWORD_text
        ${NSD_GetText} $edMYSQL_DATABASE $edMYSQL_DATABASE_text           
        ${NSD_GetText} $edMYSQL_DataSource $edMYSQL_DataSource_text         
        ${NSD_GetText} $edMYSQL_UserId $edMYSQL_UserId_text
        ${NSD_GetText} $edMYSQL_Password $edMYSQL_Password_text

;        MessageBox MB_OK $cnfCheckBox_State
 	${If} $cnfActivate_State == ${BST_CHECKED}
		FileOpen $1 $APPDATA\AsteriskNotifier\firstrun w
		FileWrite $1 'ACTIVATION_EMAIL=$edACTIVATION_EMAIL_text$\r$\n'
		FileWrite $1 'ACTIVATION_PASSWORD=$edACTIVATION_PASSWORD_text$\r$\n'
		FileWrite $1 'ASTERISK_MANAGER_PASSWORD=$edASTERISK_MANAGER_PASSWORD_text$\r$\n'
		FileWrite $1 'MYSQL_CONNECTION_STRING=Database=$edMYSQL_DATABASE_text;Data Source=$edMYSQL_DataSource_text;User Id=$edMYSQL_UserId_text;Password=$edMYSQL_Password_text$\r$\n'
		FileClose $1
	${EndIf}

FunctionEnd


Function cnfActivateClick
	Pop $cnfActivate

	${NSD_GetState} $cnfActivate $0

	${If} $0 == 1
        
	EnableWindow $lbACTIVATION_EMAIL 1
	EnableWindow $edACTIVATION_EMAIL 1
	            
	EnableWindow $lbACTIVATION_PASSWORD 1
	EnableWindow $edACTIVATION_PASSWORD 1
	            
	EnableWindow $lbASTERISK_MANAGER_PASSWORD 1
	EnableWindow $edASTERISK_MANAGER_PASSWORD 1
	            
	EnableWindow $lbMYSQL_DATABASE 1
	EnableWindow $edMYSQL_DATABASE 1
	            
	EnableWindow $lbMYSQL_DataSource 1
	EnableWindow $edMYSQL_DataSource 1
	            
	EnableWindow $lbMYSQL_UserId 1
	EnableWindow $edMYSQL_UserId 1
	            
	EnableWindow $lbMYSQL_Password 1
	EnableWindow $edMYSQL_Password 1

	${Else}
	EnableWindow $lbACTIVATION_EMAIL 0
	EnableWindow $edACTIVATION_EMAIL 0
	            
	EnableWindow $lbACTIVATION_PASSWORD 0
	EnableWindow $edACTIVATION_PASSWORD 0
	            
	EnableWindow $lbASTERISK_MANAGER_PASSWORD 0
	EnableWindow $edASTERISK_MANAGER_PASSWORD 0
	            
	EnableWindow $lbMYSQL_DATABASE 0
	EnableWindow $edMYSQL_DATABASE 0
	            
	EnableWindow $lbMYSQL_DataSource 0
	EnableWindow $edMYSQL_DataSource 0
	            
	EnableWindow $lbMYSQL_UserId 0
	EnableWindow $edMYSQL_UserId 0
	            
	EnableWindow $lbMYSQL_Password 0
	EnableWindow $edMYSQL_Password 0
	${EndIf}

	${NSD_GetState} $cnfActivate $cnfActivate_State
;        MessageBox MB_OK $cnfActivate_State
FunctionEnd




Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "AsteriskNotifier_setup.exe"
InstallDir "$APPDATA\AsteriskNotifier"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show




Section "MainSection" SEC02
  SetOutPath "$APPDATA\AsteriskNotifier"
  SetOverwrite ifnewer
  CreateDirectory "$SMPROGRAMS\AsteriskNotifier"
  CreateDirectory "$APPDATA\AsteriskNotifier"
  CreateShortCut "$DESKTOP\AsteriskNotifier.lnk" "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe"
  CreateShortCut "$SMPROGRAMS\AsteriskNotifier\AsteriskNotifier.lnk" "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe"
  SetOutPath "$APPDATA\AsteriskNotifier"
  File "Asterisk.NET.dll"
  File "AsteriskNotifier.exe"
  File "MySql.Data.dll"

SectionEnd

Section -AdditionalIcons
  CreateShortCut "$SMPROGRAMS\AsteriskNotifier\Uninstall.lnk" "$APPDATA\AsteriskNotifier\uninst.exe"
  CreateShortCut "$SMPROGRAMS\AsteriskNotifier\AsteriskNotifier.lnk" "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe"
SectionEnd

Section -Post
  WriteUninstaller "$APPDATA\AsteriskNotifier\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$APPDATA\AsteriskNotifier\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function .onInit

  nsProcess::_FindProcess "AsteriskNotifier.exe" $R0
  Pop $0
  StrCmp $0 "0" +1 +3
  MessageBox MB_ICONEXCLAMATION|MB_OK "Пожалуйста закройте AsteriskNotifier для продолжения установки." /SD IDOK
  Abort


FunctionEnd

Function .onInstSuccess
FunctionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) успешно удалена."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Хотите удалить $(^Name)?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$DESKTOP\AsteriskNotifier.lnk"

  Delete "$APPDATA\AsteriskNotifier\license.rtf"
  Delete "$APPDATA\AsteriskNotifier\readme.rtf"
  Delete "$APPDATA\AsteriskNotifier\sv.url"
  Delete "$APPDATA\AsteriskNotifier\uninst.exe"
  Delete "$APPDATA\AsteriskNotifier\Asterisk.NET.dll"
  Delete "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe"
  Delete "$APPDATA\AsteriskNotifier\MySql.Data.dll"
  Delete "$APPDATA\AsteriskNotifier\AsteriskNotifier.exe.config"

  RMDir /r $SMPROGRAMS\AsteriskNotifier
  RMDIR /r $APPDATA\AsteriskNotifier

  Delete "$APPDATA\AsteriskNotifier"
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"

  SetAutoClose true
SectionEnd
