; Script generated by the HM NIS Edit Script Wizard.
; HM NIS Edit Wizard helper defines
!include nsDialogs.nsh
!define PRODUCT_NAME "AsteriskPhoneAgent"
!define PRODUCT_VERSION "2.1.14"
!define PRODUCT_PUBLISHER "Zheltov Anton"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\AsteriskPhoneAgent.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsteriskPhoneAgent"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

!include nsDialogs.nsh
!include LogicLib.nsh


XPStyle on


; MUI 1.67 compatible ------

!include "MUI.nsh"
; Welcome page


!insertmacro MUI_PAGE_WELCOME


!insertmacro MUI_PAGE_LICENSE "license.rtf"

; Directory page

!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES

; Finish page
!define MUI_FINISHPAGE_RUN "$APPDATA\AsteriskPhoneAgent\AsteriskPhoneAgent.exe" 
;!define MUI_FINISHPAGE_SHOWREADME "readme.rtf"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES


; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------


Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "AsteriskPhoneAgent_setup.exe"
InstallDir "$APPDATA\AsteriskPhoneAgent"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show




Section "MainSection" SEC02
  SetOutPath "$APPDATA\AsteriskPhoneAgent"
  SetOverwrite ifnewer
  CreateDirectory "$SMPROGRAMS\AsteriskPhoneAgent"
  CreateDirectory "$APPDATA\AsteriskPhoneAgent"
  CreateShortCut "$DESKTOP\AsteriskPhoneAgent.lnk" "$APPDATA\AsteriskPhoneAgent\AsteriskPhoneAgent.exe"
  CreateShortCut "$SMPROGRAMS\AsteriskPhoneAgent\AsteriskPhoneAgent.lnk" "$APPDATA\AsteriskPhoneAgent\AsteriskPhoneAgent.exe"
  SetOutPath "$APPDATA\AsteriskPhoneAgent"
  File "Asterisk.NET.dll"
  File "Asterisk.NET.pdb"
  File "AsteriskPhoneAgent.exe"
  File "AsteriskPhoneAgent.exe.Config"
  
  File "MySql.Data.dll"

SectionEnd

Section -AdditionalIcons
  CreateShortCut "$SMPROGRAMS\AsteriskPhoneAgent\Uninstall.lnk" "$APPDATA\AsteriskPhoneAgent\uninst.exe"
  CreateShortCut "$SMPROGRAMS\AsteriskPhoneAgent\AsteriskPhoneAgent.lnk" "$APPDATA\AsteriskPhoneAgent\AsteriskPhoneAgent.exe"
SectionEnd

Section -Post
  WriteUninstaller "$APPDATA\AsteriskPhoneAgent\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$APPDATA\AsteriskPhoneAgent\AsteriskPhoneAgent.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$APPDATA\AsteriskPhoneAgent\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$APPDATA\AsteriskPhoneAgent\AsteriskPhoneAgent.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function .onInit

  ExecWait "TaskKill /IM AsteriskPhoneAgent.exe /F"
  Pop $0


FunctionEnd

Function .onInstSuccess
FunctionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) deleted."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Want to delete $(^Name)?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$DESKTOP\AsteriskPhoneAgent.lnk"

  Delete "$APPDATA\AsteriskPhoneAgent\license.rtf"
  Delete "$APPDATA\AsteriskPhoneAgent\uninst.exe"
  Delete "$APPDATA\AsteriskPhoneAgent\Asterisk.NET.dll"
  Delete "$APPDATA\AsteriskPhoneAgent\Asterisk.NET.pdb"

  Delete "$APPDATA\AsteriskPhoneAgent\AsteriskPhoneAgent.exe"
  Delete "$APPDATA\AsteriskPhoneAgent\MySql.Data.dll"
  Delete "$APPDATA\AsteriskPhoneAgent\AsteriskPhoneAgent.exe.config"

  RMDir /r $SMPROGRAMS\AsteriskPhoneAgent
  RMDIR /r $APPDATA\AsteriskPhoneAgent

  Delete "$APPDATA\AsteriskPhoneAgent"
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"

  SetAutoClose true
SectionEnd
